# -*- coding: utf-8 -*-
"""batch_norm_vs_layer_norm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wKMXmDVAHExYp7GZVgTeySEnxFftlmof

# batch norm vs layer norm

L'idée ici est de visualiser l'impact de la batch norm et de la layer norm sur un batch de points.

On va donc générer un nuage de B points, dans un espace de $e=3$ caractéristiques.
"""

import numpy as np

B = 100
e = 3

m = [3, -2, 5 ]
s = [1, 3, 3 ]
data = np.random.normal(loc = m, scale = s, size=(B,e))

origin = np.zeros_like(data)

import matplotlib.pyplot as plt


fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')

ax.scatter(data[:,0], data[:,1], data[:,2], marker='o',c="blue")
ax.scatter(origin[:,0], origin[:,1], origin[:,2], marker='o', c="red")


plt.show()

# batch norm

m_b = np.mean(data,axis=0)
s_b = np.std(data,axis=0)
print(m_b)
print(s_b)

data_b_norm = (data -m_b)/s_b



print (np.mean(data_b_norm,axis=0),np.std(data_b_norm,axis=0))

# layer norm

m_b = np.mean(data,axis=1)
s_b = np.std(data,axis=1)
#print(m_b)
#print(s_b)

data_l_norm = ((data.transpose() -m_b)/s_b).transpose()

#print (np.mean(data_b_norm,axis=1),np.std(data_b_norm,axis=1))

fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')

ax.scatter(data[:,0], data[:,1], data[:,2], marker='o',c="blue")
ax.scatter(data_b_norm[:,0], data_b_norm[:,1], data_b_norm[:,2], marker='+')
ax.scatter(origin[:,0], origin[:,1], origin[:,2], marker='o', c="red")
ax.scatter(data_l_norm[:,0], data_l_norm[:,1], data_l_norm[:,2], marker='x',c="green")

plt.axis([-10,10,-10,10,-10,10])

plt.show()